import Ionicons from '@expo/vector-icons/Ionicons';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Brand, Button, Card, ChoiceChip, EmptyState, IconButton, PageHeader, Screen, sharedStyles } from '@/components/ui';
import { colors, fonts } from '@/constants/theme';
import { getHealthSummary, listRecords } from '@/lib/database';
import { MedicalRecord, RecordType, ageAt, formatBytes, formatDate, recordTypes } from '@/types/models';

export default function RecordsScreen() {
  const [records, setRecords] = useState<MedicalRecord[]>([]);
  const [birthDate, setBirthDate] = useState('');
  const [query, setQuery] = useState('');
  const [type, setType] = useState<RecordType | 'All'>('All');
  const [view, setView] = useState<'list' | 'timeline'>('list');
  const load = useCallback(() => { Promise.all([listRecords(), getHealthSummary()]).then(([items, summary]) => { setRecords(items); setBirthDate(summary.birthDate); }); }, []);
  useFocusEffect(load);
  const filtered = useMemo(() => records.filter(record => {
    const text = `${record.title} ${record.provider} ${record.notes} ${record.type}`.toLowerCase();
    return (type === 'All' || record.type === type) && text.includes(query.trim().toLowerCase());
  }), [records, query, type]);
  const years = useMemo(() => Object.entries(filtered.reduce<Record<string, MedicalRecord[]>>((groups, record) => { const year = record.date.slice(0, 4) || 'Undated'; (groups[year] ??= []).push(record); return groups; }, {})).sort(([a], [b]) => b.localeCompare(a)), [filtered]);

  return <Screen>
    <View style={styles.top}><Brand/><IconButton icon="settings-outline" label="Settings" onPress={() => router.push('/settings')}/></View>
    <PageHeader eyebrow="MY HEALTH DOSSIER" title="Record library" subtitle="Your documents, ready when you need them." action={<Button title="Add" icon="add" onPress={() => router.push('/record/edit')}/>}/>
    <View style={styles.privacy}><Ionicons name="lock-closed-outline" size={20} color={colors.green}/><Text style={styles.privacyText}>Stored locally on this device. Nothing is uploaded.</Text></View>
    <Card style={styles.toolbar}><View style={styles.search}><Ionicons name="search" size={18} color={colors.muted}/><TextInput value={query} onChangeText={setQuery} placeholder="Search records" placeholderTextColor={colors.muted} style={styles.searchInput}/>{query ? <Pressable onPress={() => setQuery('')}><Ionicons name="close-circle" size={18} color={colors.muted}/></Pressable> : null}</View><View style={styles.filters}><ChoiceChip label="All" selected={type === 'All'} onPress={() => setType('All')}/>{recordTypes.map(item => <ChoiceChip key={item} label={item} selected={type === item} onPress={() => setType(item)}/>)}</View><View style={styles.viewRow}><Text style={sharedStyles.body}>{filtered.length} {filtered.length === 1 ? 'record' : 'records'}</Text><View style={styles.switch}><Pressable onPress={() => setView('list')} style={[styles.switchButton, view === 'list' && styles.switchActive]}><Ionicons name="list" size={17} color={view === 'list' ? colors.green : colors.muted}/><Text style={view === 'list' ? styles.switchTextActive : styles.switchText}>List</Text></Pressable><Pressable onPress={() => setView('timeline')} style={[styles.switchButton, view === 'timeline' && styles.switchActive]}><Ionicons name="git-commit-outline" size={17} color={view === 'timeline' ? colors.green : colors.muted}/><Text style={view === 'timeline' ? styles.switchTextActive : styles.switchText}>Timeline</Text></Pressable></View></View></Card>
    <View style={styles.results}>{filtered.length === 0 ? <EmptyState icon={records.length ? 'search-outline' : 'folder-open-outline'} title={records.length ? 'No matching records' : 'Your library starts here'} body={records.length ? 'Try another search or record type.' : 'Add a report, prescription, scan, or care note to keep it easy to find.'} action={!records.length ? <Button title="Add your first record" icon="document-attach-outline" onPress={() => router.push('/record/edit')}/> : undefined}/> : view === 'list' ? filtered.map(record => <RecordRow record={record} key={record.id}/>) : years.map(([year, items]) => <View key={year} style={styles.year}><View style={styles.yearHeader}><Text style={styles.yearTitle}>{year}</Text><Text style={sharedStyles.body}>{items.length} records</Text></View><View style={styles.timeline}>{items.map(record => <Pressable key={record.id} onPress={() => router.push(`/record/${record.id}`)} style={styles.timelineRow}><View style={[styles.dot, record.important && { backgroundColor: colors.error }]}/><View style={styles.timelineDate}><Text style={styles.timelineDateMain}>{formatDate(record.date)}</Text>{birthDate && ageAt(record.date, birthDate) !== null && <Text style={styles.timelineAge}>Age {ageAt(record.date, birthDate)}</Text>}</View><Card style={styles.timelineCard}><Text style={sharedStyles.label}>{record.type}{record.important ? '  ·  IMPORTANT' : ''}</Text><Text style={styles.recordTitle}>{record.title}</Text>{record.provider ? <Text style={sharedStyles.body}>{record.provider}</Text> : null}</Card></Pressable>)}</View></View>)}</View>
  </Screen>;
}

function RecordRow({ record }: { record: MedicalRecord }) { return <Pressable onPress={() => router.push(`/record/${record.id}`)}><Card style={styles.record}><View style={[styles.fileIcon, record.fileType.startsWith('image/') && { backgroundColor: colors.sage }]}><Ionicons name={record.fileType.startsWith('image/') ? 'image-outline' : 'document-text-outline'} size={24} color={record.fileType.startsWith('image/') ? colors.green : colors.blue}/></View><View style={{ flex: 1 }}><Text numberOfLines={1} style={styles.recordTitle}>{record.title}</Text><Text style={styles.recordMeta}>{record.type} · {formatDate(record.date)}{record.provider ? ` · ${record.provider}` : ''}</Text><Text style={styles.recordMeta}>{formatBytes(record.fileSize)}{record.important ? '  ·  Important' : ''}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.muted}/></Card></Pressable>; }

const styles = StyleSheet.create({
  top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 15 }, privacy: { flexDirection: 'row', gap: 11, alignItems: 'center', padding: 14, borderLeftWidth: 2, borderLeftColor: colors.green, backgroundColor: colors.surfaceSoft, marginBottom: 15 }, privacyText: { flex: 1, color: colors.muted, fontFamily: fonts.sans, fontSize: 12, lineHeight: 18 },
  toolbar: { padding: 14, gap: 14 }, search: { flexDirection: 'row', alignItems: 'center', gap: 9, borderWidth: 1, borderColor: colors.line, borderRadius: 9, paddingHorizontal: 12, backgroundColor: colors.backgroundRaised }, searchInput: { flex: 1, height: 46, color: colors.text, fontFamily: fonts.sans },
  filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, viewRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, switch: { flexDirection: 'row', borderWidth: 1, borderColor: colors.line, borderRadius: 8, padding: 3 }, switchButton: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingVertical: 7, paddingHorizontal: 10, borderRadius: 5 }, switchActive: { backgroundColor: colors.surfaceSoft }, switchText: { color: colors.muted, fontFamily: fonts.sansMedium, fontSize: 11 }, switchTextActive: { color: colors.green, fontFamily: fonts.sansMedium, fontSize: 11 },
  results: { gap: 10, marginTop: 14 }, record: { flexDirection: 'row', alignItems: 'center', gap: 13, padding: 14 }, fileIcon: { width: 44, height: 50, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.line, borderRadius: 6 }, recordTitle: { color: colors.text, fontFamily: fonts.sansMedium, fontSize: 14, marginBottom: 5 }, recordMeta: { color: colors.muted, fontFamily: fonts.sans, fontSize: 11, lineHeight: 17 },
  year: { marginTop: 10 }, yearHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }, yearTitle: { color: colors.text, fontFamily: fonts.serif, fontSize: 29 }, timeline: { borderLeftWidth: 1, borderLeftColor: colors.line, marginLeft: 6, paddingLeft: 16, gap: 13 }, timelineRow: { flexDirection: 'row', alignItems: 'center', gap: 11 }, dot: { position: 'absolute', left: -22, width: 11, height: 11, borderRadius: 6, backgroundColor: colors.green }, timelineDate: { width: 76, gap: 3 }, timelineDateMain: { color: colors.text, fontFamily: fonts.sansMedium, fontSize: 11 }, timelineAge: { color: colors.muted, fontFamily: fonts.sans, fontSize: 10 }, timelineCard: { flex: 1, padding: 13 },
});
