import Ionicons from '@expo/vector-icons/Ionicons';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Button, Card, EmptyState, Notice, PageHeader, Screen, sharedStyles } from '@/components/ui';
import { colors, fonts } from '@/constants/theme';
import { deleteCollection, getCollection, listRecords, setCollectionRecords } from '@/lib/database';
import { openDocument, shareDocument } from '@/lib/files';
import { CareCollection, MedicalRecord, formatDate } from '@/types/models';

export default function CollectionDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [collection, setCollection] = useState<CareCollection | null>(null); const [records, setRecords] = useState<MedicalRecord[]>([]); const [managing, setManaging] = useState(false); const [selected, setSelected] = useState<string[]>([]); const [query, setQuery] = useState(''); const [error, setError] = useState('');
  const load = useCallback(() => { Promise.all([getCollection(id), listRecords()]).then(([group, items]) => { setCollection(group); setRecords(items); setSelected(items.filter(record => record.collectionIds.includes(id)).map(record => record.id)); }); }, [id]); useFocusEffect(load);
  const collectionRecords = useMemo(() => records.filter(record => record.collectionIds.includes(id)), [records, id]);
  const years = useMemo(() => Object.entries(collectionRecords.reduce<Record<string, MedicalRecord[]>>((groups, record) => { (groups[record.date.slice(0, 4)] ??= []).push(record); return groups; }, {})).sort(([a], [b]) => b.localeCompare(a)), [collectionRecords]);
  const matching = records.filter(record => `${record.title} ${record.provider} ${record.type}`.toLowerCase().includes(query.toLowerCase()));
  if (!collection) return <Screen><Text style={sharedStyles.body}>Opening collection…</Text></Screen>;
  const remove = () => Alert.alert(`Delete “${collection.name}”?`, 'Its records will stay in your library.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { await deleteCollection(id); router.replace('/(tabs)/collections'); } }]);
  const saveMembership = async () => { try { await setCollectionRecords(id, selected); setManaging(false); load(); } catch { setError('Collection membership could not be saved.'); } };
  const fileAction = async (action: () => Promise<void>) => { try { await action(); } catch { setError('The original file could not be opened.'); } };
  return <Screen><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={colors.muted}/><Text style={styles.backText}>Collections</Text></Pressable><PageHeader eyebrow="CARE COLLECTION" title={collection.name} subtitle={collection.description || 'A collection of related health records.'}/>{error && <Notice error>{error}</Notice>}
    <Card style={styles.notes}><View style={styles.panelTitle}><Ionicons name="create-outline" size={20} color={colors.green}/><Text style={styles.panelTitleText}>Private notes</Text></View><Text style={collection.notes ? styles.noteText : sharedStyles.body}>{collection.notes || 'No private notes added.'}</Text><View style={styles.noteActions}><Button title="Edit collection" icon="pencil" kind="secondary" onPress={() => router.push({ pathname: '/collection/edit', params: { id } })}/><Button title="Delete" icon="trash-outline" kind="danger" onPress={remove}/></View></Card>
    {managing ? <Card style={styles.manage}><Text style={styles.manageTitle}>Choose records</Text><View style={styles.search}><Ionicons name="search" size={18} color={colors.muted}/><TextInput value={query} onChangeText={setQuery} placeholder="Search your library" placeholderTextColor={colors.muted} style={styles.searchInput}/></View><View style={styles.checklist}>{matching.map(record => { const checked = selected.includes(record.id); return <Pressable key={record.id} onPress={() => setSelected(current => checked ? current.filter(value => value !== record.id) : [...current, record.id])} style={[styles.checkRow, checked && styles.checked]}><Ionicons name={checked ? 'checkbox' : 'square-outline'} size={22} color={checked ? colors.green : colors.muted}/><View style={{ flex: 1 }}><Text style={styles.recordTitle}>{record.title}</Text><Text style={sharedStyles.body}>{record.type} · {formatDate(record.date)}</Text></View></Pressable>; })}</View><View style={styles.manageActions}><Button title="Cancel" kind="secondary" onPress={() => { setManaging(false); setSelected(collectionRecords.map(record => record.id)); }} style={{ flex: 1 }}/><Button title="Save records" icon="checkmark" onPress={saveMembership} style={{ flex: 1 }}/></View></Card> : <Card style={styles.timelinePanel}><View style={styles.timelineHeader}><View><Text style={styles.manageTitle}>Record timeline</Text><Text style={sharedStyles.body}>{collectionRecords.length} {collectionRecords.length === 1 ? 'record' : 'records'}</Text></View><Button title="Manage" icon="options-outline" kind="secondary" onPress={() => setManaging(true)}/></View>{collectionRecords.length === 0 ? <EmptyState icon="calendar-outline" title="No records here yet" body="Choose records from your library to begin this timeline." action={<Button title="Choose records" onPress={() => setManaging(true)}/>}/> : <View style={styles.years}>{years.map(([year, items]) => <View key={year}><Text style={styles.year}>{year}</Text><View style={styles.yearItems}>{items.map(record => <View key={record.id} style={styles.timelineRow}><View style={[styles.dot, record.important && { backgroundColor: colors.error }]}/><View style={{ flex: 1 }}><Text style={sharedStyles.label}>{formatDate(record.date)} · {record.type}</Text><Pressable onPress={() => router.push(`/record/${record.id}`)}><Text style={styles.recordTitle}>{record.title}</Text></Pressable>{record.provider ? <Text style={sharedStyles.body}>{record.provider}</Text> : null}</View><Pressable onPress={() => fileAction(() => openDocument(record.fileUri, record.fileType))} style={styles.fileButton}><Ionicons name="open-outline" size={19} color={colors.muted}/></Pressable><Pressable onPress={() => fileAction(() => shareDocument(record.fileUri, record.fileType))} style={styles.fileButton}><Ionicons name="share-outline" size={19} color={colors.muted}/></Pressable></View>)}</View></View>)}</View>}</Card>}
  </Screen>;
}
const styles = StyleSheet.create({ back: { flexDirection: 'row', alignItems: 'center', gap: 7, paddingTop: 18 }, backText: { color: colors.muted, fontFamily: fonts.sans, fontSize: 12 }, notes: { gap: 14, marginBottom: 14 }, panelTitle: { flexDirection: 'row', alignItems: 'center', gap: 9, paddingBottom: 13, borderBottomWidth: 1, borderBottomColor: colors.line }, panelTitleText: { color: colors.text, fontFamily: fonts.sansMedium, fontSize: 15 }, noteText: { color: colors.text, fontFamily: fonts.serif, fontStyle: 'italic', fontSize: 16, lineHeight: 25 }, noteActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, manage: { gap: 14 }, manageTitle: { color: colors.text, fontFamily: fonts.serif, fontSize: 23 }, search: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: colors.line, borderRadius: 9, paddingHorizontal: 12 }, searchInput: { height: 46, flex: 1, color: colors.text }, checklist: { gap: 8 }, checkRow: { flexDirection: 'row', alignItems: 'center', gap: 11, borderWidth: 1, borderColor: colors.line, borderRadius: 9, padding: 12 }, checked: { borderColor: colors.green, backgroundColor: colors.sage }, recordTitle: { color: colors.text, fontFamily: fonts.sansMedium, fontSize: 14, marginVertical: 5 }, manageActions: { flexDirection: 'row', gap: 9 }, timelinePanel: { padding: 0, overflow: 'hidden' }, timelineHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 17, borderBottomWidth: 1, borderBottomColor: colors.line }, years: { padding: 17, gap: 21 }, year: { color: colors.text, fontFamily: fonts.serif, fontSize: 28, marginBottom: 11 }, yearItems: { borderLeftWidth: 1, borderLeftColor: colors.line, paddingLeft: 15, gap: 12 }, timelineRow: { flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.line, paddingBottom: 12 }, dot: { position: 'absolute', left: -21, width: 11, height: 11, borderRadius: 6, backgroundColor: colors.green }, fileButton: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center' } });
